M48
; DRILL file {KiCad 7.0.2-0} date 2024 January 15, Monday 07:51:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-15T07:51:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X47.066Y-51.765
X47.066Y-109.779
X70.079Y-51.791
X70.079Y-109.779
T0
M30
